### ISSUE TITLE
Reversed Slider

### ISSUE THREAD

**Issue by AndrejHronco** [sghall/react-compound-slider#17]
How would I reverse the start point of the handle from the left of the slider to the right, basically, it would act similarly to the reversed mode but also have the handle reversed along with the slider values.

**Comment by sghall** [comment]
Hey there.  What do you mean "reverse the start point of the handle"?  Not sure what the start point is.  The handles do move to the location of their value when you reverse it.  Can you explain a little more?

**Comment by AndrejHronco** [comment]
Hi, sorry, i should've included images before to clarify.
This is a regular slider that the handle and track highlight (light blue)
![regular-slider](https://user-images.githubusercontent.com/1925905/39332879-ae2ab7fc-495d-11e8-9f34-d6c7084b2349.png)

This is the slider that i'm trying to implement. where the handle and track highlight (skyblue) start at the right side. 
![reversed-slider](https://user-images.githubusercontent.com/1925905/39332880-ae4444d8-495d-11e8-9cec-5c1ef369d016.png)

Loving using the slider component so far. 
Thanks for your work

**Comment by sghall** [comment]
Oh,  I see.  Yep, a picture speaks a thousand words.  Yeah,  there's a few ways to do that.  

The `Tracks` component gives you an array of tracks.  If it's a single slider there's two possible tracks.  One on the left and one on the right (there's always handles + 1 possible tracks in any slider).  You can just manipulate the array of tracks however you want.  

I also add a "left" and "right" prop to the `Tracks` component as a convenience because that's the most common thing i.e. you want to toggle showing the outside tracks.  Probably the easiest thing in your case, if it's just a single slider, is to just toggle the left and right props based on if it's reversed.

Assuming you have some kind of `reversed` flag, something like...
```
          <Slider.Tracks left={reversed ? true : false} right={reversed ? false : true}>
            {({ tracks, getTrackProps }) => (
              <div className="slider-tracks">
                {tracks.map(({ id, source, target }) => (
                  <Track
                    key={id}
                    source={source}
                    target={target}
                    getTrackProps={getTrackProps}
                  />
                ))}
              </div>
            )}
          </Slider.Tracks>
```
Modified from the examples here:
https://github.com/sghall/react-compound-slider/blob/634496a1088af19ec5bb3675f31be8911180d957/docs/src/pages/slider-demos/horizontal/Example1.js#L73

Make sense?

**Comment by AndrejHronco** [comment]
This worked perfectly!
Thanks you
