### ISSUE TITLE
Add the possibility to customize the scale

### ISSUE THREAD

**Issue by tbassetto** [sghall/react-compound-slider#27]
### Feature requests

Probably out of scope for this package but I will ask anyway: I would like to use the slider to adjust the frequency for an audio device. The thing is the possible values goes from 20 to 20000 and my first issue is that I guess the following warning in the console:
> Warning: react-compound-slider: Increase step value. Found 19,981 values in range.

Is it really an issue to have that many steps? Can I silence the warning?

Also, in theory configuring the frequency works best with a logarithmic scale. Do you think that customizing the scale could be a feature added to this component?

**Comment by sghall** [comment]
Hey there.  Yeah, I put the 10k limit in there pretty arbitrarily to let people know that I'm actually calculating these steps up front.  So if your steps are very fine grained it can be kind of expensive.  

I guess my thinking was you only have so many pixels on the screen so there's kind of a natural limit to how fine you can allow someone to adjust.  You don't want to have a step value of 2 or 5 on 20k values? The step value will be bring that down below the limit. Anyway, the limit is just something I put in there and it's never come up. Maybe we should make that a prop with a default value? 

Yeah,  I haven't had a need to do a logarithmic scale, but seems like you can do that by just using a d3-scale (or whatever) to translate the values and the labels.  Since you can control all the rendering you could just do that with the existing components.   Right?  

Was just looking at: https://github.com/d3/d3-scale#log-scales.  Probably, should have an example of this but seems like it would be easy to do.  Let me know if you run into problems on this.  If you want to setup a Codsandbox or something probably get this worked out.

**Comment by tbassetto** [comment]
I'll have a stab at it and keep you posted.

**Comment by nickpolet** [comment]
Just curious if you got anywhere with this? Keen to use log scale with this slider. Would appreciate some pointers on progressing if possible.
