### ISSUE TITLE
cpu load issue on big value for domain

### ISSUE THREAD

**Issue by FirelightFlagboy** [sghall/react-compound-slider#34]
### Problem or feature description:
Cpu Load issue and tab crash when using big value in domain.
I want to use a Slider for time interval so i use unix timestamp in domain do to so.
when i change the value for smaller one (like 0 to 100) it work no problem

### Steps to reproduce (for problems):
```React
<Slider domain={[1388530800000, 1535752800000]}
    values={[ 1530752800000 ]}
    rootStyle={{
        position: 'relative',
        width: '100%',
        height: 80,
        border: '1px solid steelblue',
    }}>
    <div style={{
        position: 'absolute',
        width: '100%',
        height: 10,
        marginTop: 35,
        borderRadius: 5,
        backgroundColor: '#8B9CB6',
    }} />
</Slider>
```
### Versions (for problems):
```Json
{
    "react-compound-slider": "^0.16.1",
    "react": "^16.3.2",
}
```

Browser: Chrome 69.0.3497.100

Operating System: Windows 10

**Comment by FirelightFlagboy** [comment]
for the moment, i'll use feature scaling method

**Comment by sghall** [comment]
Hi, there. I think you just need to set the **step** prop.  The slider is always broken into discrete steps based on the domain and the step. For a unix timestamp you'd do a step of 60 * 60 for hours,  60 * 60 * 24 for days, etc.  I think for your case it would be days because hours would be too granular for such a long time span.

**Comment by FirelightFlagboy** [comment]
i will try this
thank for the help

**Comment by sghall** [comment]
I also just released a new version.  It will throw on 1 million steps in the range and warns on 100k.  RCS shouldn't allow unlimited items to get pushed into the range.  To be honest, I haven't tried doing a time range slider.  Because the steps in the range are pre-calculated and each value must be a valid step, it may require some work to use this library.  Be good to have an example.  Let me know what your experience is.

**Comment by FirelightFlagboy** [comment]
thanks it work
