### ISSUE TITLE
Adding tooltip?

### ISSUE THREAD

**Issue by thunderkid** [sghall/react-compound-slider#46]
Great library. Thanks.
Is there a way to add a tooltip to the handle, as several sliders provide? I've tried using `react-tooltip-lite` to wrap the `Handle`, but that seems to give a tooltip that centers on the rail and never moves.

**Comment by sghall** [comment]
Hey there.  Good question.  This library avoids getting involved in what's rendered in your component, so you would have to make your own handle component with a tooltip.

**Comment by thunderkid** [comment]
Makes sense. Thanks.

**Comment by sghall** [comment]
Let's re-open this.

 Seems to me, the most common scenario is to put a tooltip above the handle when sliding.  This is not something I personally use but I put together this basic example to demonstrate how this can be done...

https://codesandbox.io/s/n0v0k64zmp

<img width="577" alt="screen shot 2019-01-20 at 8 20 11 pm" src="https://user-images.githubusercontent.com/4615775/51451082-d30bb780-1cf0-11e9-9e1b-b3985867026d.png">

To me, nothing needs to be added to the library to do this kind of tooltip.  This library doesn't get involved in styles and what content gets rendered.  You can implement these kinds of tooltips however you like.  That's the value of this library.  `rc-slider` more than 6X the size (29.5kb gzipped) and is very difficult to get styled to match your application.

The other scenario that has come up where you have tooltips that show as you mouse over the rail.

@thunderkid provided a link in https://github.com/sghall/react-compound-slider/issues/49
https://plyr.io/

<img width="335" alt="screen shot 2019-01-20 at 8 22 59 pm" src="https://user-images.githubusercontent.com/4615775/51451195-66dd8380-1cf1-11e9-966f-d266e28c56f9.png">

This one can't be done because you need a way to get the value as the mouse moves over the rail.  I think that's what is needed.  Pass a function to the rail component (and the `Tracks` component but I think that's less useful) that you can pass an event and it will give the value (and the percent).  You can then just make your own rail component which adds and removes its own mouseover listeners.

Make sense?  Are there other scenarios that can't be accomplished using this?

@thunderkid, do you want to implement this?  If not I can add it.

**Comment by thunderkid** [comment]
> Make sense? Are there other scenarios that can't be accomplished using this?

Yes, I believe there are. 

If you look at, eg, plyr.io or youtube, you see that while a handle is active the tooltip remains visible, even if your mouse moves off the header as you slide. This is nice, standard, behavior. Now if you release off-header, the tooltip should vanish. But if you release on-header, it should transition into a header-hovering tooltip - it should not vanish and then reappear only once you jiggle the mouse, but it should just transition nicely. (Youtube gets this particular feature wrong; plyr.io and others get it right.) If you click on the track, the header should jump to that point (if it doesn't violate some header separation constraint) and be captured. The tooltip should immediately transition from a track-hover style to a header-captured style. There are other edge cases that you want to guard against too - eg if you have a `mode-3` double header, and you drag one through the other, you shouldn't see a second tooltip appearing for a moment as the headers cross. I suspect that might happen with your approach if you're not careful.

I think basic tooltip functionality can be implemented very easily, but to get it to behave just right requires more work.

My original PR contained examples with tooltips doing all of these things correctly. Based on your suggestion (that I perhaps misinterpreted) I've since reimplemented my same functionality using a tooltip callback instead, so that the parent's responsible for actually rendering the tooltip, but `Slider` tells it what to render and when. It cleaned up the code a bit, but I fear it would still make for a large PR.

**Comment by sghall** [comment]
Yep,  you brought up some good points @thunderkid.  Had not thought about some of those details. I added passing down the `activeHandleID` and a function called `getEventData` that you send an event to and it gives you back an object with `{ value, percent}`.  I add some tooltip demos to the site.  Take a look and tell me what you think.  I think it looks pretty good but you have consistently come up with good feedback so let me know.

https://sghall.github.io/react-compound-slider/#/slider-demos/tooltips

This was released in 0.19.0

**Comment by thunderkid** [comment]
Yes, that's got the basic functionality, but I think you'll agree that the code's starting to look a little less elegant ;)

Also, there are a couple of edge cases that aren't quite right:
1) On the pushable slider, grab the left handle by its right side. Move it slowly to the right, pushing the other one over. You'll notice two tooltips flickering.
2) This one's harder to reproduce - look at your first example. Grab one handle, and slide it through the other one. Release it. You'll (sometimes) see a flash where the tooltip momentarily appears on the wrong handle. (I think this might have something to do with handle id's changing order in setState but I'm not sure ...)

And to allow for different tooltip states for grabbed vs non-grabbed you'll have some more patches to apply. If you expand things later and, eg, want ticks to have tooltips that don't interfere with a dragged handle, then that'll be more patches still.  Sure, with enough fiddling, things can certainly be done this way, but I don't honestly see any particular advantage over the more centralized state-management method that I proposed...

**Comment by sghall** [comment]
Yeah, I think you lost me.   There's a very big difference in this code.  It doesn't render the entire slider on every mouse move when there's tooltips on the rail.  I appreciate your input.  Thanks!
