### ISSUE TITLE
[Question] Range length check (not more than 1M values)

### ISSUE THREAD

**Issue by releasedin** [sghall/react-compound-slider#60]
Problem or feature description:

`Slider range is too large. Increase step value`

I have a range slider with two handlers (using to filter the price)
I can't put the domain min 0, max 1M (or more) and step 1 because there is a check to not have values greater than 1M.
![image](https://user-images.githubusercontent.com/20513656/52943059-f1f37d00-3374-11e9-87b6-8e39718ae73a.png)

I don't know if this is a good check because in real world app the min/max values are dynamic configurable and it's possible to have more than 1M ranges.

My question is:
**Can you explain way and how can I rid of that?**

Versions:
React-Compound-Slider: 0.20.1
React: Latest
Browser: Chrome Latest
Operating System: Windows 10

**Comment by sghall** [comment]
Hey there,  I appreciate the question. This has come up a few times and I probably should add a section in the docs on this.  The slider calculates the full range (all the steps) ahead of time that's why there's a limit.  I don't want people to have this enormous array in memory without realizing it. This makes sense to me, but I'm open to hearing about particular use cases or alternative ideas.  

Here's why I think this makes sense.  You can't actually allow someone to select more than a few thousand items accurately on any interface.  The reason is there's only so many pixels on the screen, so there's always a certain amount of inaccuracy built in.  There is always an implicit "step" value being applied to their selection. 

Here's an [rc-slider](https://github.com/react-component/slider/) with a min of 0 and max of 1,000,000. 
https://codesandbox.io/s/qlvnn98n84

I put a "diff" up there to show you how much the value is changing on each move.  Try resizing the window. The amount of that diff will change as the window size changes because the number of pixels available.  That, to me, is an arbitrary step value being chosen for you.  

Small window has a diff of 2,793:
<img width="360" alt="screen shot 2019-02-18 at 4 01 13 pm" src="https://user-images.githubusercontent.com/4615775/52980244-73a7d280-3396-11e9-8d8d-521b4289af77.png">

Larger window has a diff of 816:
<img width="457" alt="screen shot 2019-02-18 at 4 03 04 pm" src="https://user-images.githubusercontent.com/4615775/52980310-b9fd3180-3396-11e9-815c-82a0d2c260da.png">

That's why there's a max of 1M on the range in RCS.   Realistically, you should have a step of at least 1,000 on this large a number.  This library to just forces you to be explicit on the step value applied.

**Comment by releasedin** [comment]
Thank you for answer.
I'm agree, you are right, a huge array in the memory is not a good job, but how about to make this max length configurable? 
I propose this, because each developer is responsible for his work, so let's offer a choice to have or not these huge values in the memory. 
I think these kind of restrictions should be configurable.

What you think about this?

**Comment by sghall** [comment]
Yeah, that's fair.  I just released version 0.21.1 to address this.  I made the warning point to this ticket so people will be directed here to understand what the issue was.  Please feel free to add any comments or notes on this ticket.

First, let me just make it 100% clear that, to me, **this should be a non-issue for most developers**.  In my opinion the numbers we're talking about here should never be used on any well-designed interface.  **If you find yourself struggling with this issue I would step back and ask if there's a better way to get the information you need from the user.** (see above comments for more on this)  That said, there's likely some cases where you are just prototyping or just need to get something working and this library shouldn't stop you from doing that.

There were several warnings/issues to consider this is what I came up with:

Two new props:
1. `maxSteps` - defaults to 500,000.
2. `rangeWarnings` - defaults to true.

**The slider will never throw now for this issue**  (before it threw an error on 1M steps in the range).  It will warn on 500,000 items and you can adjust that threshold with the `maxSteps` prop.

Alternatively, you can switch off all warnings related to the range with the `rangeWarnings` prop set to false.  Defaulting to true allows all developers who are using really large numbers to be aware how the range works read this ticket. 

The other issue that comes up with the range is that the domain (max - min) is not evenly divisible by the step e.g. domain = [1, 103] and step = 5.  This can cause some weird behavior.  Setting `rangeWarnings` to false will turn off warnings for BOTH this issue and the range being too large.

I'm going to close this ticket.  Try out the latest and open this back up if there's any additional issues.

Cheers.
