### ISSUE TITLE
Handles - adding props

### ISSUE THREAD

**Issue by JoeZman** [sghall/react-compound-slider#71]
Is it possible to provide props to each Handle on initialization?  We treat Handles as milestones during a time period.  We would like to render per handle specific tag information.  For example, when the user hovers over a handle, display a label, description, time, etc (metadata).  Wondering how we can specify object (prop) information per handle?  This would also sold a secondary problem we have, some our handles are rendered differently.  For example, simple circles, while another is a "scrubber", like you find a video player as the time elapses.  So one handle is constantly moving, while the others are milestones along that path.  Make sense?

React-Compound-Slider: 1.10

React: 16.0.0

Browser: Chrome 72.0.3626.121

Operating System: Windows xx

**Comment by sghall** [comment]
Hey.  Yeah,  good question.   I know what you mean because that's how I thought it should work originally.  You can see that the handles get stored as a { key, val } object in the state.  

https://github.com/sghall/react-compound-slider/blob/d0a12f251dca91c4fa544987b53b37ce419b9655/src/Slider/utils.js#L81

I think you just want to supply your own keys (the "key" is the id that is passed to the handle) so you know what it is.

Then, when the onChange, etc fires you need the { key, val } objects...

https://github.com/sghall/react-compound-slider/blob/d0a12f251dca91c4fa544987b53b37ce419b9655/src/Slider/Slider.js#L445

Right now, you just get the values.

Not sure the library, as is, could support this without too much disruption or making it really kludgy.  It's certainly possible to do it, by forking it.  Just not sure it could support that use case and the existing cleanly.  

I would look at PR, but it's not a given that it would get merged.  You are welcome to fork the repo of course and maintain version that supports that feature.
