### ISSUE TITLE
Is there a way to reset the handle position on button click

### ISSUE THREAD

**Issue by marexandre** [sghall/react-compound-slider#90]
More a question then an issues - is there a way to reset the slider to an initial state?

For example I have a domain that's `[0, 10]`, on page load my values is `[0]`, after the user slides the slider I want to show a `reset` button to reset the slider back to `0` or some other default value between `0` and `10`.

Is this possible?

**Comment by sghall** [comment]
Hey there.  Sure.  The slider works as a controlled component so you can set the values to whatever you want at anytime.  Just maintain that state above the slider itself.

**Comment by marexandre** [comment]
Thank you for your reply.
I've made an example where I'm doing what you suggested (I hope).
When clicking on the reset button the first time it will set the slider to `0`, but when I move the slider one more time and click on the reset button, it does not reset it to `0`. 

https://codesandbox.io/embed/react-compound-slider-1j9st

Hope this example helps.

**Comment by sghall** [comment]
Yeah,  I see the issue.   This is a little quirky. I'd like to rework this logic at some point.   It will update once to [0] but the second time it doesn't because the last `values` prop it saw was [0] (it does an inspection of the values not just object equality).  To fix it, just manage a values array in state and don't think of the defaults as a separate piece of information.  Use the `onChange` prop  to keep the the `values` in state up to date. 

Here's an updated sandbox:
https://codesandbox.io/s/react-compound-slider-reset-example-g5m1e

**Comment by marexandre** [comment]
Thank you for the example! Think I've got it working. Closing.
